<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\DLL_injector.dll" />
    <None Remove="Resources\NTE_launcher_hook.dll" />
    <None Remove="Resources\NTE_unlockfps_plugin.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\DLL_injector.dll" />
    <EmbeddedResource Include="Resources\NTE_launcher_hook.dll" />
    <EmbeddedResource Include="Resources\NTE_unlockfps_plugin.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.1.0-alpha0181">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

</Project>
